### ISSUE TITLE
ParsePromise resolved after being rejected

### ISSUE THREAD

**Issue by ghugues** [ParsePlatform/Parse-SDK-JS#143]
One of my scripts failed with the following log :
```
Script failed with error 100 : XMLHttpRequest failed: {}
/.../node_modules/parse/lib/node/ParsePromise.js:58
        throw new Error('A promise was resolved even though it had already been ' + (this._resolved ? 'resolved' : 'rejected') + '.');
        ^

Error: A promise was resolved even though it had already been rejected.
    at ParsePromise.resolve (/.../node_modules/parse/lib/node/ParsePromise.js:58:15)
    at xhr.onreadystatechange (/.../node_modules/parse/lib/node/RESTController.js:105:19)
    at dispatchEvent (/.../node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/.../node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/.../node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
```
Looking at `RESTController.js`, it seems that if the call to `JSON.parse()` throws an exception, the promise will be rejected and then resolved because the `promise.resolve()` call is outside the `try/catch` block. And it's not the only place where this can happen.
I have no idea how a 2** HTTP response could result in unparseable JSON though.

**Comment by andrewimm** [comment]
As far as I know, this was fixed in recent versions of the SDK. If you look at https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/RESTController.js#L102 in master, the resolve block will not take place after the reject has happened.

**Comment by ghugues** [comment]
My mistake, I was using version 1.6.9 of the SDK. I has indeed been fixed in master, although something similar still exists here : https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/RESTController.js#L53

**Comment by andrewimm** [comment]
Fixed the IE 9 case.
