### ISSUE TITLE
Issue using GeoPoint.current()

### ISSUE THREAD

**Issue by jorourke** [ParsePlatform/Parse-SDK-JS#336]
I see the error: 

```
/usr/local/bin/node /Users/james/Documents/workspace/fb-parse-server/clientjs/test_session_queries.es6
/Users/james/Documents/workspace/fb-parse-server/node_modules/parse/lib/node/ParseGeoPoint.js:210
      navigator.geolocation.getCurrentPosition(function (location) {
      ^

ReferenceError: navigator is not defined
    at Function.current (/Users/james/Documents/workspace/fb-parse-server/node_modules/parse/lib/node/ParseGeoPoint.js:210:7)
    at Object.<anonymous> (/Users/james/Documents/workspace/fb-parse-server/clientjs/test_session_queries.es6:41:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
```

This is how I'm using the code:

```
var trainingSession = new Parse.Object('TrainingSession');
current = null;
Parse.GeoPoint.current({
    success: function (point) {
        //use current location
        console.log(point);
        current = point;
    }
});
```

I'm not sure how I should be using that but it does seem that navigator global seems absent.

**Comment by andrewimm** [comment]
`GeoPoint.current()` is not supported in Node.js. A server does not have a GPS, nor a way to tell Node.js its location if it did.
